import {
  blog1,
  blog2,
  blog3,
  c1,
  c2,
  c3,
  c4,
  c5,
  c6,
  counter1,
  counter2,
  counter3,
  counter4,
  t1,
  t2,
  t3,
  t4,
  t5,
  t6,
  t7,
  t8,
  team1,
  team2,
  team3,
  team4,
  team5,
  team6,
  team7,
  team8,
  isev_annual_meeting_2024,
  tiny_talk_series,
  tiny_talk_series_1,
  society_launch,
  society_launch_1,
  webinar,
  webinar_1,
  meetings,
  webinars,
  training_workshop,
  journal,
  rc1,
} from "./images";

export const AchievementCounter = [
  {
    icon: counter1,
    num: 82 + "k",
    sector: "Enrolled Students",
  },
  {
    icon: counter2,
    num: 460,
    sector: "Academic Programs",
  },
  {
    icon: counter3,
    num: 20,
    sector: "Certified Studens",
  },
  {
    icon: counter4,
    num: 200,
    sector: "Award Winnig",
  },
];

export const blogArticleData = [
  {
    title: "Fashion and Luxury Fashion in a Changing",
    img: c1,
  },
  {
    title: "Creative Writing Through Storytelling",
    img: c2,
  },
  {
    title: "Product Manager Learn The Skills & Job",
    img: c3,
  },
  {
    title: "The Power of Podcast for Storytelling",
    img: c4,
  },
];

export const courseData = [
  {
    id: [0, "marketing", "design"],
    post: "Art & desing",
    title: "Webinars",
    price: "$29.28",
    img: webinar_1,
    ratings: "4.5",
    date: "Stay Tuned",
    location: "",
    link:"",
  },
  {
    id: [0, "design", "finance"],
    post: ["Development"],
    price: "Free",
    title: "Society Launch",
    img: society_launch_1,
    ratings: "4.5",
    date: "2 Dec, 2023",
    location: "AHERF Auditorium, Apollo hospitals, Jubilee Hills, Hyderabad",
    link:"",
  },
  {
    id: [0, "marketing", "design"],
    post: "Drawing",
    price: "$72.39",
    title: "TinyTalk Series",
    img: tiny_talk_series_1,
    ratings: "4.5",
    date: "Every alternate Thursday 9:00 AM to 10:00 AM",
    location: "Online Event",
    link:"",
  },
  {
    id: [0, "marketing"],
    post: "Tecknology",
    price: "$49.33",
    title: "ISEV Annual Meeting 2024",
    img: isev_annual_meeting_2024,
    ratings: "4.5",
    date: "MAY 8-12, 2024",
    location: "Melbourne Convention and Exhibition Centre Melbourne, Australia",
    link:"https://talley.eventsair.com/isev2024",
  },
];

export const eventsData=[
  {
    img:journal,
    title:"Journal Club",
    date:"Ongoing",
    location:"Offline / Online",
    heading:"A Collaborative Platform for Advanced Scientific Exploration",
    paragraph:"Welcome to the Extracellular Vesicle Research Journal Club! Hosted by the renowned Indian Extracellular Vesicles Society (IEVS), our Journal Club is an exceptional interactive forum for scientists, researchers, and enthusiasts interested in extracellular vesicle (EV) research. This collaborative initiative is committed to deepening the collective expertise in EV biology, disease mechanisms, and potential clinical applications, including diagnostics and therapeutics.",
    subheading1:"Features In-Depth Discussions and Peer Reviews in EV Research:",
    subheading1_content:"Our Journal Club sessions are designed to facilitate comprehensive discussions and critical evaluations of peer-reviewed scientific articles in extracellular vesicle research. This enriching format explores the multifaceted roles of EVs in biology and medicine, offering invaluable insights for established scientists and emerging researchers.",
    subheading2:"Meeting Schedule Focused on EV Research Topics",
    subheading2_content:"The Journal Club convenes bi-monthly, on the 2nd and 4th Friday of every month. Each session is meticulously planned to focus on an extracellular vesicle science topic or theme. Active members are encouraged to contribute by proposing relevant scientific papers for future discussions.",
    subheading3:"How to Join Our Exclusive EV Research Journal Club",
    subheading3_content:"To become an exclusive member of our Journal Club, send an email to info@ievs.in indicating your specific topics of interest or selected scientific papers for discussion. Upon review, we will allocate a presentation slot in an upcoming session. We look forward to welcoming you to our Extracellular Vesicle Research Journal Club and embarking on a journey of discovery and collaboration in the fascinating world of EV research!",
    guest_name:"John Doe",
    guest_designation:"Lorem",
    guest_img:rc1,
  },
  {
    img:training_workshop,
    title:"Training / Workshop",
    date:"Ongoing",
    location:"Offline / Online",
    heading:"Empowering the Next Generation of EV Researchers",
    paragraph:"Extracellular vesicles (EVs) have gained prominence as a ground-breaking domain in biomedical research, attributed to their pivotal roles in intercellular communication, disease pathogenesis, and therapeutic potential. As this burgeoning field continues to evolve, there is a pressing need for researchers who are both well-versed in the theoretical aspects and proficient in the practical applications of EV biology. To address this demand, the Indian Extracellular Vesicles Society (IEVS) offers a variety of specialised training programs and workshops. These educational initiatives are designed to equip scientists, clinicians, and students with a comprehensive understanding of the complexities of EV biology, including state-of-the-art isolation techniques, characterisation methodologies, and diverse applications in diagnostics, therapeutics, and more.",
    guest_name:"John Doe",
    guest_designation:"Lorem",
    guest_img:rc1,
  },
  {
    img:webinars,
    title:"Webinars",
    date:"Ongoing",
    location:"Offline / Online",
    heading:"Bridging the Gap in Extracellular Vesicle Research Globally",
    paragraph:"Webinars have become an indispensable tool in the fast-paced world of extracellular vesicle (EV) research, serving as a dynamic platform for knowledge dissemination, global research collaboration, and continuous learning. These virtual seminars afford scientists, clinicians, and students the luxury of interacting with leading experts in the field, posing questions, and gaining insights into the latest advancements—all from the comfort of their location. Conducted by the Indian Extracellular Vesicles Society (IEVS), our webinars are specifically designed to meet the diverse educational needs of the EV research community. They provide an inclusive, flexible, and convenient medium for professionals and aspiring researchers to stay abreast of cutting-edge developments, novel methodologies, and emerging applications in diagnostics, therapeutics, and beyond.",
    guest_name:"John Doe",
    guest_designation:"Lorem",
    guest_img:rc1,
  },
  {
    img:meetings,
    title:"Meetings",
    date:"Ongoing",
    location:"Offline / Online",
    heading:"A Hub for Collaborative Exploration in Extracellular Vesicle Research",
    paragraph:"The Indian Extracellular Vesicles Society (IEVS) is a dynamic, inclusive community of multidisciplinary professionals—ranging from researchers and scientists to clinicians and industry experts. United by a shared commitment to advancing extracellular vesicle (EV) research, our society focuses on enriching our understanding of EV biology, diverse functions, and practical applications through collective research efforts and knowledge exchange.",
    subheading1:"Regular Meetings to Foster EV Research Collaboration",
    subheading1_content:"We host regular member-exclusive meetings that are meticulously planned to stimulate in-depth discussions, foster valuable networking opportunities, and facilitate the exchange of the latest research findings in extracellular vesicles.",
    subheading2:"Stay Connected and Updated",
    subheading2_content:"To learn more about our upcoming meetings or to become a member of our vibrant community, please visit our official website at www.ievs.in. Keep up-to-date with our latest news, research updates, and announcements by subscribing to our newsletter or following us on our social media platforms. We warmly invite you to become part of our initiative and join our exclusive meetings, thereby contributing to the collective advancement of the fast-paced and promising field of extracellular vesicle research.",
    guest_name:"John Doe",
    guest_designation:"Lorem",
    guest_img:rc1,
  },
]

export const topicsData = [
  { logo: t1, title: "Data Science", quantity: "68 Courses" },
  { logo: t2, title: "UI/UX Design", quantity: "UI/UX Design" },
  { logo: t3, title: "Modern Physics", quantity: "68 Courses" },
  { logo: t4, title: "Music Production", quantity: "45 Courses" },
  { logo: t5, title: "Data Science", quantity: "68 Courses" },
  { logo: t6, title: "Finances", quantity: "68 Courses" },
  { logo: t7, title: "Global Science", quantity: "75 Courses" },
  { logo: t8, title: "Game Design", quantity: "12 Courses" },
];

export const teamData = [
  { img: team1, name: "Erics Widget", title: "UI/UX Designer" },
  { img: team2, name: "Daniel Steven", title: "Developer" },
  { img: team3, name: "Nelson Decosta", title: "Digital Marketer" },
  { img: team4, name: "Selina Gomez", title: "UI/UX Designer" },
];
export const instructorData = [
  { img: team5, name: "Erics Widget", title: "UI/UX Designer" },
  { img: team6, name: "Daniel Steven", title: "Developer" },
  { img: team7, name: "Nelson Decosta", title: "Digital Marketer" },
  { img: team8, name: "Selina Gomez", title: "UI/UX Designer" },
];

export const blogsData = [
  {
    img: blog1,
    type: "education",
    position: "admin",
    date: "jan 29, 2022",
    title: "Professional Mobile Painting and Sculpting",
  },
  {
    img: blog2,
    type: "education",
    position: "admin",
    date: "jan 29, 2022",
    title: "Professional Ceramic Moulding for Beginners",
  },
  {
    img: blog3,
    type: "education",
    position: "admin",
    date: "jan 29, 2022",
    title: "Education Is About Create Leaders For Tomorrow",
  },
];
